import * as THREE from 'three';
import {createChengdu} from './chengdu.js';
import {OrbitControls} from 'three/addons/OrbitControls.js';
const $=s=>document.querySelector(s), TAU=Math.PI*2;
let seed=82931;const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
const scene=new THREE.Scene();scene.background=new THREE.Color('#e5ece3');scene.fog=new THREE.Fog('#e5ece3',480,1350);
const camera=new THREE.PerspectiveCamera(40,innerWidth/innerHeight,.2,1500);const homePosition=()=>new THREE.Vector3(155,191,270).multiplyScalar(Math.min(2,Math.max(1,.8/camera.aspect)));camera.position.copy(homePosition());
let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true});}catch(e){$('#loading').innerHTML='<p>浏览器暂时无法启动 WebGL，请开启硬件加速后重新打开。</p>';throw e;}
renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;$('#scene').appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.065;controls.minDistance=12;controls.maxDistance=1000;controls.maxPolarAngle=Math.PI*.485;controls.target.set(0,2,0);controls.autoRotateSpeed=.32;
const hemi=new THREE.HemisphereLight('#f4ffff','#8a9262',1.9);scene.add(hemi);
const sun=new THREE.DirectionalLight('#fff8dd',2.7);sun.position.set(-100,180,100);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-180,right:180,top:160,bottom:-160,near:1,far:450});sun.shadow.bias=-.0005;sun.shadow.normalBias=.35;scene.add(sun);
const fill=new THREE.DirectionalLight('#c7e9dc',.8);fill.position.set(100,70,-130);scene.add(fill);
const world=new THREE.Group();scene.add(world);
const mat=(color,opts={})=>new THREE.MeshStandardMaterial({color,roughness:.85,metalness:0,...opts});
const stone=mat('#e4e5cc'),earth=mat('#d3d9b9'),roof=mat('#648777'),wood=mat('#8a5b3c'),cream=mat('#f0e9cc'),gold=mat('#d7b450',{metalness:.45,roughness:.32}),glass=mat('#477f7b',{metalness:.35,roughness:.3}),road=mat('#d4d5bd');
function mesh(geometry,material,parent=world){const m=new THREE.Mesh(geometry,material);parent.add(m);return m;}
function box(x,y,z,w,h,d,material,parent=world){const m=mesh(new THREE.BoxGeometry(w,h,d),material,parent);m.position.set(x,y+h/2,z);m.castShadow=true;m.receiveShadow=true;return m;}
function cylinder(x,y,z,r1,r2,h,material,n=16,parent=world){const m=mesh(new THREE.CylinderGeometry(r1,r2,h,n),material,parent);m.position.set(x,y+h/2,z);m.castShadow=true;m.receiveShadow=true;return m;}
function ball(x,y,z,r,material,parent=world,detail=1){const m=mesh(new THREE.IcosahedronGeometry(r,detail),material,parent);m.position.set(x,y,z);m.castShadow=true;return m;}
function line(points,color,width=.1,parent=world){const curve=new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(...p)));const m=mesh(new THREE.TubeGeometry(curve,Math.max(8,points.length*4),width,5,false),typeof color==='string'?mat(color):color,parent);return m;}
function shapeMesh(points,material,y=.13,parent=world){const s=new THREE.Shape();points.forEach(([x,z],i)=>i?s.lineTo(x,-z):s.moveTo(x,-z));s.closePath();const m=mesh(new THREE.ShapeGeometry(s),material,parent);m.rotation.x=-Math.PI/2;m.position.y=y;m.receiveShadow=true;return m;}
function roundedRect(w,h,r){const s=new THREE.Shape();const x=-w/2,y=-h/2;s.moveTo(x+r,y);s.lineTo(x+w-r,y);s.quadraticCurveTo(x+w,y,x+w,y+r);s.lineTo(x+w,y+h-r);s.quadraticCurveTo(x+w,y+h,x+w-r,y+h);s.lineTo(x+r,y+h);s.quadraticCurveTo(x,y+h,x,y+h-r);s.lineTo(x,y+r);s.quadraticCurveTo(x,y,x+r,y);return s;}
const base=mesh(new THREE.ExtrudeGeometry(roundedRect(290,214,9),{depth:5,bevelEnabled:true,bevelSize:1.5,bevelThickness:1.1,bevelSegments:3,steps:1}),earth);base.rotation.x=-Math.PI/2;base.position.y=-6.3;base.receiveShadow=true;
const ground=mesh(new THREE.PlaneGeometry(3000,3000),mat('#e5ece3'));ground.rotation.x=-Math.PI/2;ground.position.y=-7;ground.receiveShadow=true;
// Continuous mountain terrain, cut into flat-shaded triangular facets.
const peaks=[[-104,-69,26,31,28],[-82,-64,28,28,27],[-113,-26,21,25,27],[-80,-28,25,24,23],[-60,-52,16,21,21],[-106,20,15,24,17],[-65,24,12,17,14],[-120,74,10,18,16],[112,81,10,22,19],[-36,-88,5,25,13]];
function height(x,z){let h=0;for(const [a,b,v,sx,sz]of peaks)h+=v*Math.exp(-(((x-a)/sx)**2+((z-b)/sz)**2)*1.45);let out=Math.max(0,h-.8);const basin=((x+106)/10)**2+((z+70)/17)**2;if(basin<1.25)out=Math.min(out,21.9+Math.max(0,basin-1)*50);return out;}
const terrainGeo=new THREE.PlaneGeometry(284,208,125,92);terrainGeo.rotateX(-Math.PI/2);let pa=terrainGeo.attributes.position;for(let i=0;i<pa.count;i++)pa.setY(i,height(pa.getX(i),pa.getZ(i))+.01);terrainGeo.computeVertexNormals();const terrainFlat=terrainGeo.toNonIndexed();const colors=[];let v=new THREE.Vector3();for(let i=0;i<terrainFlat.attributes.position.count;i+=3){let h=terrainFlat.attributes.position.getY(i);let c=new THREE.Color(h>.7?'#a1b67c':'#dee1c6');if(h>.7)c.lerp(new THREE.Color('#7e9e65'),Math.min(h/65,.7));c.multiplyScalar(.965+rnd()*.065);for(let j=0;j<3;j++)colors.push(c.r,c.g,c.b);}terrainFlat.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));const terrain=mesh(terrainFlat,mat('#ffffff',{vertexColors:true,flatShading:true}));terrain.receiveShadow=true;terrain.castShadow=true;
// Lakes and river share a subtle animated surface shader.
const waterUniform={time:{value:0},night:{value:0}};
const water=mat('#58b3ab',{roughness:.35,metalness:.12,transparent:true,opacity:.94});water.onBeforeCompile=s=>{s.uniforms.uTime=waterUniform.time;s.uniforms.uNight=waterUniform.night;s.vertexShader='varying vec3 vWater;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nvWater = (modelMatrix * vec4(position,1.0)).xyz;');s.fragmentShader='uniform float uTime; uniform float uNight; varying vec3 vWater;\n'+s.fragmentShader;s.fragmentShader=s.fragmentShader.replace('#include <color_fragment>','#include <color_fragment>\nfloat wave = sin(vWater.x*.53+vWater.z*.68+uTime*.6)*sin(vWater.z*.37-vWater.x*.28+uTime*.35); float ripple=pow(max(0.0,wave),9.0); diffuseColor.rgb += (ripple*.13+wave*.024)*(1.0-uNight*.55);');};
const lake={x:-22,z:-10,rx:24,rz:21};function lakeR(x,z){return ((x-lake.x)/lake.rx)**2+((z-lake.z)/lake.rz)**2;}
const lakePoints=Array.from({length:90},(_,i)=>{let a=i/90*TAU,r=1+.06*Math.sin(a*3)+.025*Math.cos(a*7);return[lake.x+Math.cos(a)*lake.rx*r,lake.z+Math.sin(a)*lake.rz*r];});
shapeMesh(lakePoints,water,.35);line([...lakePoints,lakePoints[0]].map(([x,z])=>[x,.32,z]),'#cbd7b2',.7);
const riverPath=new THREE.CatmullRomCurve3([[-146,0,52],[-105,0,47],[-64,0,43],[-21,0,44],[20,0,49],[57,0,44],[87,0,20],[107,0,-9],[145,0,-25]].map(p=>new THREE.Vector3(...p)));
const riverPts=riverPath.getPoints(180);let riverWidth=13;const riverShape=[];for(let i=0;i<riverPts.length;i++){let tangent=riverPath.getTangent(i/180);riverShape.push([riverPts[i].x-tangent.z*riverWidth/2,riverPts[i].z+tangent.x*riverWidth/2]);}for(let i=riverPts.length-1;i>=0;i--){let tangent=riverPath.getTangent(i/180);riverShape.push([riverPts[i].x+tangent.z*riverWidth/2,riverPts[i].z-tangent.x*riverWidth/2]);}shapeMesh(riverShape,water,.4);
function riverDistance(x,z){let d=1e6;for(let i=0;i<riverPts.length;i+=3)d=Math.min(d,(riverPts[i].x-x)**2+(riverPts[i].z-z)**2);return Math.sqrt(d);}
// Grand canal and wetland channels.
shapeMesh([[7,-104],[9,-104],[12,-58],[10,-18],[7,-18],[8,-57]],water,.32);
const wetland=[];for(let i=0;i<9;i++){let x=-49+rnd()*23,z=-72+rnd()*15;const pts=Array.from({length:18},(_,j)=>{let a=j/18*TAU;return[x+Math.cos(a)*(3+rnd()*3),z+Math.sin(a)*(2+rnd()*2)];});shapeMesh(pts,water,height(x,z)+.25);wetland.push([x,z]);}
// Narrow mountain lake and rivers around the outskirts.
const qlake=Array.from({length:60},(_,i)=>{let a=i/60*TAU;return[-106+Math.cos(a)*9,-70+Math.sin(a)*16];});shapeMesh(qlake,water,22.5);
for(let i=0;i<3;i++)shapeMesh([[89+i*9,67],[91+i*9,67],[97+i*9,101],[95+i*9,101]],water,.28);
// Instanced trees: thousands of individually scaled crowns with a handful of draw calls.
const trees=[];function addTree(x,z,s=1,y=null){trees.push({x,z,y:y??height(x,z),s,rot:rnd()*TAU,color:new THREE.Color().setHSL(.23+rnd()*.1,.26+rnd()*.15,.32+rnd()*.2)});}
for(let i=0;i<6400;i++){let x=-138+rnd()*275,z=-99+rnd()*197,h=height(x,z);if(riverDistance(x,z)<10||lakeR(x,z)<1.15||((x+106)/10)**2+((z+70)/17)**2<1)continue;if(h>2||(x<-40&&rnd()>.65)||(z>80&&rnd()>.4))addTree(x,z,.7+rnd()*.85);}
for(let i=0;i<115;i++){let a=i/115*TAU;addTree(lake.x+Math.cos(a)*25.3,lake.z+Math.sin(a)*22.3,.8,.35);}
function makeTrees(){const dummy=new THREE.Object3D();const trunks=new THREE.InstancedMesh(new THREE.CylinderGeometry(.13,.18,1.3,5),wood,trees.length);const crowns=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(1,0),mat('#ffffff',{flatShading:true}),trees.length);trees.forEach((t,i)=>{dummy.position.set(t.x,t.y+.65*t.s,t.z);dummy.scale.set(t.s,t.s,t.s);dummy.rotation.set(0,t.rot,0);dummy.updateMatrix();trunks.setMatrixAt(i,dummy.matrix);dummy.position.y=t.y+1.9*t.s;dummy.scale.set(t.s*.95,t.s*1.35,t.s*.95);dummy.updateMatrix();crowns.setMatrixAt(i,dummy.matrix);crowns.setColorAt(i,t.color);});world.add(trunks,crowns);crowns.castShadow=true;crowns.receiveShadow=true;}
// Window atlas, also used as an emissive map at night.
const texCanvas=document.createElement('canvas');texCanvas.width=128;texCanvas.height=256;const tx=texCanvas.getContext('2d');tx.fillStyle='#d4dece';tx.fillRect(0,0,128,256);for(let j=0;j<20;j++)for(let i=0;i<8;i++){tx.fillStyle=rnd()>.15?'#819f98':'#bbcbc0';tx.fillRect(i*16+4,j*12+4,7,6);}const wintex=new THREE.CanvasTexture(texCanvas);wintex.colorSpace=THREE.SRGBColorSpace;
const lightCanvas=document.createElement('canvas');lightCanvas.width=128;lightCanvas.height=256;const lx=lightCanvas.getContext('2d');lx.fillStyle='#000';lx.fillRect(0,0,128,256);for(let j=0;j<20;j++)for(let i=0;i<8;i++){if(rnd()>.38){lx.fillStyle=rnd()>.2?'#ffe3a0':'#b7e5dc';lx.fillRect(i*16+4,j*12+4,7,6);}}const lightTex=new THREE.CanvasTexture(lightCanvas);lightTex.colorSpace=THREE.SRGBColorSpace;
const facade=mat('#ffffff',{map:wintex,emissiveMap:lightTex,emissive:'#ffc96b',emissiveIntensity:0});const roofmat=mat('#d7ddcc');const citymat=[facade,facade,roofmat,roofmat,facade,facade];
const buildings=[];
function excluded(x,z){return lakeR(x,z)<1.5||riverDistance(x,z)<12||height(x,z)>1.2||(Math.abs(x-9)<3&&z<-17)||((x-44)**2+(z-23)**2<24**2)||((x-69)**2+(z-65)**2<18**2)||((x+22)**2+(z-16)**2<8**2);}
for(let iz=0;iz<47;iz++)for(let ix=0;ix<59;ix++){let x=-26+ix*2.8,z=-98+iz*4.1;if(x>138||excluded(x,z)||rnd()<.2)continue;if(ix%8===0||iz%7===0)continue;let heightB=1.7+rnd()*4.8;if(x>15&&x<78&&z>-48&&z<85)heightB+=rnd()*9;buildings.push({x:x+(rnd()-.5)*.8,z:z+(rnd()-.5)*.7,w:1.25+rnd()*.9,d:1.55+rnd()*.95,h:heightB});}
const city=new THREE.InstancedMesh(new THREE.BoxGeometry(1,1,1),citymat,buildings.length);const dummy=new THREE.Object3D();buildings.forEach((b,i)=>{dummy.position.set(b.x,b.h/2+.05,b.z);dummy.scale.set(b.w,b.h,b.d);dummy.updateMatrix();city.setMatrixAt(i,dummy.matrix);city.setColorAt(i,new THREE.Color().setHSL(.2+rnd()*.06,.08+rnd()*.12,.65+rnd()*.2));});city.castShadow=true;city.receiveShadow=true;world.add(city);
// Small settlements in the valley.
for(let i=0;i<90;i++){let x=-130+rnd()*65,z=66+rnd()*28;if(height(x,z)>2||riverDistance(x,z)<12)continue;box(x,height(x,z),z,1.8,1.8,2.4,cream);const r=cylinder(x,height(x,z)+1.8,z,0,1.8,1,roof,4);r.rotation.y=Math.PI/4;}
// Raised causeways with tree-lined promenades.
function causeway(points,width=1.1){line(points,'#dce0c3',width);for(let i=0;i<points.length-1;i++){let a=new THREE.Vector3(...points[i]),b=new THREE.Vector3(...points[i+1]);for(let k=0;k<a.distanceTo(b);k+=2.1){let p=a.clone().lerp(b,k/a.distanceTo(b));addTree(p.x+.7,p.z,.6,p.y+.15);}}}
causeway([[-42,.7,-22],[-28,.7,-14],[-12,.7,-8],[-.5,.7,-4]],.6);causeway([[-37,.65,7],[-26,.65,2],[-15,.65,-4]],.45);
for(const [x,z,r]of[[-26,-3,2.7],[-15,3,2.1],[-32,-13,1.8]]){cylinder(x,.3,z,r,r,.65,earth,24);for(let i=0;i<7;i++)addTree(x+(rnd()-.5)*r,z+(rnd()-.5)*r,.6,.9);}
for(let i=0;i<3;i++){cylinder(-23+i*3,.4,-3,.35,.45,2.5,cream,10);cylinder(-23+i*3,2.9,-3,.5,.65,.35,roof,8);}
function pagoda(x,z,floors=5,scale=1){const g=new THREE.Group();g.position.set(x,height(x,z),z);g.scale.setScalar(scale);world.add(g);cylinder(0,0,0,4,4,.6,stone,8,g);for(let f=0;f<floors;f++){let y=.6+f*2.8,r=2.6-f*.14;cylinder(0,y,0,r,r,2.3,cream,8,g);for(let j=0;j<8;j++){let a=j/8*TAU;const window=box(Math.cos(a)*(r+.015),y+.5,Math.sin(a)*(r+.015),.72,1.35,.09,glass,g);window.rotation.y=-a+Math.PI/2;cylinder(Math.cos(a+Math.PI/8)*(r+.18),y,Math.sin(a+Math.PI/8)*(r+.18),.1,.1,2.5,wood,6,g);}cylinder(0,y+2.1,0,r*.73,r+1,1.1,gold,8,g);cylinder(0,y+2.14,0,r+1.05,r+1.05,.13,cream,8,g);}cylinder(0,floors*2.8+.8,0,.05,.35,2,gold,8,g);ball(0,floors*2.8+2.5,0,.4,gold,g);return g;}
pagoda(-22,16,5,1);pagoda(-62,30,7,.87);pagoda(-70,-59,6,.67);
// Lingyin: tiled roofs, red columns, nested temple courts.
function temple(x,z){let y=height(x,z);const g=new THREE.Group();g.position.set(x,y,z);world.add(g);box(0,0,0,14,.7,13,stone,g);for(let k=0;k<3;k++){let zz=3-k*5;box(0,.7,zz,8,2.2,3.4,cream,g);for(let j=-3;j<=3;j+=1.5)cylinder(j,.7,zz+1.8,.12,.12,2.6,wood,6,g);const r=cylinder(0,2.8,zz,1.2,5.6,1.8,roof,4,g);r.scale.z=.64;r.rotation.y=Math.PI/4;for(let i=-5;i<=5;i++)line([[i*.65,3.25,zz-2],[i*.65,4,zz],[i*.65,3.25,zz+2]],'#7d9480',.07,g);}}temple(-62,-28);
// Longjing fields follow the hillside in parallel terrace strips.
for(let row=0;row<18;row++){const points=[];for(let i=0;i<22;i++){let x=-109+i*1.1,z=-10+row*.9+Math.sin(i*.17)*1.3;points.push([x,height(x,z)+.35,z]);}line(points,row%2?'#668547':'#7d974e',.32);}
// Qianjiang New City skyline: twin curved towers, golden conference globe and opera house.
box(43,.1,26,38,.5,27,stone);
function tower(x,z,h,r){const m=cylinder(x,.6,z,r*.85,r,h,glass,12);const edge=mat('#9cbeb1',{metalness:.3});for(let f=1;f<h;f+=1.2){const ring=mesh(new THREE.TorusGeometry(r*(1-.15*f/h)+.03,.045,3,24),edge);ring.rotation.x=Math.PI/2;ring.position.set(x,.6+f,z);}for(let i=0;i<12;i++){let a=i/12*TAU;line([[x+Math.cos(a)*r,.6,z+Math.sin(a)*r],[x+Math.cos(a)*r*.85,h+.6,z+Math.sin(a)*r*.85]],edge,.07);}return m;}
tower(40,17,31,3.2);tower(49,15,37,3.4);for(let i=0;i<16;i++){let x=28+rnd()*37,z=9+rnd()*15;if((x-40)**2+(z-17)**2<30||(x-49)**2+(z-15)**2<30)continue;box(x,.5,z,2+rnd()*2,8+rnd()*15,2+rnd()*2,glass);}
const globe=mesh(new THREE.SphereGeometry(5.1,40,28),gold);globe.position.set(49,5.8,32);globe.castShadow=true;for(let i=0;i<22;i++){const ring=mesh(new THREE.TorusGeometry(5.15,.035,3,60),mat('#e5cb7a'));ring.position.copy(globe.position);ring.rotation.y=i/22*Math.PI;}cylinder(49,.5,32,5.9,5.9,.35,cream,40);
for(let i=0;i<6;i++){const petal=mesh(new THREE.SphereGeometry(1,20,12),cream);petal.position.set(35+(i%3-1)*2.4,3.1,31+Math.floor(i/3)*3.7);petal.scale.set(2.5,3.5,2);petal.rotation.z=(i%3-1)*.22;petal.castShadow=true;}
// Olympic stadium: open bowl, stepped seats and 28 sculptural lotus petals.
const stadium=new THREE.Group();stadium.position.set(69,.4,67);world.add(stadium);
cylinder(0,0,0,13,13,.6,stone,64,stadium);const field=mesh(new THREE.CircleGeometry(6.8,64),mat('#96b986'),stadium);field.rotation.x=-Math.PI/2;field.scale.y=.67;field.position.y=.75;
for(let i=0;i<6;i++){const seat=mesh(new THREE.TorusGeometry(7.1+i*.58,.32,5,64),mat(i%2?'#d4dcca':'#c7d6c1'),stadium);seat.rotation.x=Math.PI/2;seat.scale.y=.74;seat.position.y=.8+i*.45;}
for(let i=0;i<28;i++){let a=i/28*TAU;const petal=mesh(new THREE.SphereGeometry(1,12,10),cream,stadium);petal.position.set(Math.cos(a)*10.6,3.1,Math.sin(a)*8.1);petal.scale.set(1.55,4.5,.6);petal.rotation.set(Math.sin(a)*.36,Math.PI/2-a,-Math.cos(a)*.36);petal.castShadow=true;}
const fieldLines=mat('#ecf4df');line([[-4.4,.79,-2.8],[4.4,.79,-2.8],[4.4,.79,2.8],[-4.4,.79,2.8],[-4.4,.79,-2.8]],fieldLines,.045,stadium);line([[0,.8,-2.8],[0,.8,2.8]],fieldLines,.045,stadium);
// Cable-stayed bridges and moving miniature traffic.
const traffic=[];function bridge(t,length=26){const center=riverPath.getPoint(t),tan=riverPath.getTangent(t);const g=new THREE.Group();g.position.set(center.x,1,center.z);g.rotation.y=-Math.atan2(tan.z,tan.x);world.add(g);box(0,0,0,2.8,.6,length,cream,g);box(0,.6,0,2.2,.05,length,road,g);for(let side of[-1,1]){line([[side*1.35,.9,-length/2],[side*1.35,.9,length/2]],cream,.09,g);for(let end of[-1,1]){box(side*1.1,-.8,end*length*.26,.3,12,.5,cream,g);for(let k=0;k<6;k++){line([[side*1.1,10.9,end*length*.26],[side*1.1,.8,end*length*.26+(k-2.5)*1.7]],cream,.045,g);}}}for(let i=0;i<7;i++){const car=box(i%2?.5:-.5,.8,-length/2+i*3,.45,.32,.85,mat(['#e9ede2','#c18c61','#558a87'][i%3]),g);traffic.push({car,len:length,speed:(i%2?1:-1)*(1.5+rnd()),start:rnd()});}}
bridge(.68,26);bridge(.87,27);bridge(.25,25);
// Gongchen bridge crossing the canal.
const archPoints=[];for(let i=0;i<=30;i++){let t=i/30;archPoints.push([5+t*8,1+Math.sin(t*Math.PI)*2.3,-61]);}line(archPoints,cream,.7);for(let offset of[-.75,.75])line(archPoints.map(p=>[p[0],p[1]+.8,p[2]+offset]),cream,.1);
// Boats navigate the river and West Lake.
const boats=[];function boat(x,z,scale=1,sail=false){const g=new THREE.Group();g.position.set(x,.6,z);g.scale.setScalar(scale);world.add(g);const hull=cylinder(0,0,0,.7,.5,.4,wood,6,g);hull.scale.z=2.8;box(0,.4,0,.85,.24,1.7,cream,g);if(sail){cylinder(0,.3,0,.055,.055,2.5,wood,6,g);const s=new THREE.Shape();s.moveTo(0,0);s.lineTo(1.2,0);s.lineTo(0,2.4);s.closePath();const m=mesh(new THREE.ShapeGeometry(s),cream,g);m.position.set(0,.5,0);m.material.side=THREE.DoubleSide;}else{box(0,.65,0,.8,.3,1.1,roof,g);}return g;}
for(let i=0;i<12;i++){let a=rnd()*TAU,r=5+rnd()*13;let g=boat(lake.x+Math.cos(a)*r,lake.z+Math.sin(a)*r,.55,i%4===0);boats.push({g,type:'lake',a,r,speed:.025+rnd()*.025});}for(let i=0;i<6;i++){let g=boat(0,0,.9,i%2===0);boats.push({g,type:'river',a:i/6,speed:.008+rnd()*.006});}
// Village bridges and white-walled Shaoxing courtyard houses.
for(let i=0;i<65;i++){let x=84+rnd()*42,z=78+rnd()*23;if(height(x,z)>4)continue;box(x,height(x,z),z,1.7,1.4,2.2,cream);const r=cylinder(x,height(x,z)+1.4,z,0,1.5,.8,roof,4);r.rotation.y=Math.PI/4;}
makeTrees();
// Destinations retain the hierarchy and bilingual typesetting of the reference.
const hangzhouDestinations=[
['西湖','West Lake',-22,-10,1,62,'city','三面云山，一湖碧水。苏堤与白堤把湖光轻轻分开，小瀛洲、三潭印月与慢行的游船，在掌心铺成一幅江南。','湖心三岛,堤岸漫步,舟行碧波'],
['雷峰塔','Leifeng Pagoda',-22,16,8,35,'city','八角塔身，层层飞檐。暖金色的屋顶与朱红立柱交叠，临湖而立，近看每一层檐口与栏杆。','八角塔身,分层飞檐,临湖而立'],
['灵隐山林','Lingyin & Forest',-62,-28,height(-62,-28)+5,48,'city','群山深处，古刹藏在林间。层叠殿宇、青瓦与红柱沿山势展开，树影顺着山脊延伸。','山林古刹,层叠殿宇,青瓦红柱'],
['钱江新城','Qianjiang New City',44,23,16,90,'city','钱塘江北岸，现代杭州的天际线。玻璃双塔、金色国际会议中心与花瓣形大剧院，构成日月同辉的城市客厅。','玻璃双塔,日月同辉,滨江天际线'],
['奥体大莲花','Olympic Sports Center',69,67,3,49,'city','钱塘江畔，一朵盛开的白莲。二十八片几何花瓣环绕开放式看台，草坪、碗形结构与层层座席清晰可见。','莲花花瓣,开放看台,亚运之城'],
['运河 · 拱宸桥','Grand Canal',9,-61,2,45,'city','一条运河穿城而过，一座石桥连接两岸。沿着青色水道，读一段杭州与水相伴的故事。','运河水道,石拱桥,街巷肌理'],
['六和塔','Liuhe Pagoda',-62,30,10,40,'city','高塔镇江，重檐叠影。七层外观与八角结构立于山麓，越过树梢，可以远眺钱塘江。','重檐古塔,临江山麓,八角结构'],
['钱塘江','Qiantang River',24,49,1,110,'city','一江碧水穿过山城。桥梁跨越两岸，船只缓缓前行，城市的轮廓在江面两侧徐徐展开。','跨江大桥,江上行舟,两岸风光'],
['西溪湿地','Xixi Wetland',-40,-66,6,58,'city','水巷、绿洲与林地相互交织。小尺度池塘散落在山麓，留下一片轻盈安静的城市留白。','交错水网,湿地绿洲,城中自然'],
['龙井茶山','Longjing Tea Fields',-97,-1,height(-97,-1)+2,45,'nature','整齐的茶垄沿着山势舒展。走近看，平行的绿色曲线在坡面上层层起伏，勾勒西湖以西的茶山风景。','梯田茶垄,连绵山势,龙井春色'],
['临安 · 青山湖','Qingshan Lake',-106,-70,23,55,'nature','山色拥抱一湾清水。林木环湖而立，低多边形山体以柔和的明暗变化，铺陈远郊的静谧。','山中湖泊,水岸森林,青山叠翠'],
['富阳 · 富春山水','Fuchun Landscape',-99,70,4,63,'nature','富春江畔，村落散落于山水之间。青瓦民居与缓缓流动的江水，拼起一幅微缩山居图。','富春山居,江畔村落,青瓦民居'],
['桐庐山水','Tonglu Mountains',-123,37,7,68,'nature','沿江向山里走去，树影与山脊接连展开。远处的村落、近处的林木，共同构成舒展的山水层次。','山水长卷,沿江漫行,远山近树'],
['绍兴水乡','Shaoxing Water Town',106,86,3,62,'nature','白墙黛瓦依水而居，细长水道穿过村落。以压缩的空间尺度，呈现江南水乡的肌理与日常。','白墙黛瓦,纵横水巷,江南村落'],
['宝石山 · 保俶塔','Baoshi Hill',-70,-59,height(-70,-59)+7,43,'nature','秀塔从绿色山脊间探出头来。沿山林靠近，在树影与层层塔檐之间，回望微缩杭州。','山脊秀塔,低多边形,湖山相望']
].map((d,i)=>({name:d[0],en:d[1],x:d[2],z:d[3],y:d[4],distance:d[5],type:d[6],copy:d[7],tags:d[8],index:i}));
let selected=null,tabType='city',flight=null,roaming=false,roamTime=0,roamIndex=0,showLabels=true,runningWater=true,mode='day',clean=false;
const cityConfigs={hangzhou:{name:'杭州',title:'山水杭州',en:'HANGZHOU',seal:'江<br>南',subtitle:'一城山色，半城湖光。',destinations:hangzhouDestinations,group:world},chengdu:{name:'成都',title:'烟火成都',en:'CHENGDU',seal:'天<br>府',subtitle:'一江锦色，满城烟火。'}};
let activeCity='hangzhou',destinations=hangzhouDestinations,chengdu=null;
function renderLabels(){
 $('#labels').replaceChildren();
 for(const d of destinations){const el=document.createElement('button');el.className='label';el.textContent=d.name;el.setAttribute('aria-label',`前往${d.name}`);el.onclick=()=>selectDestination(d.index);$('#labels').append(el);d.el=el;d.point=new THREE.Vector3(d.x,d.labelY??d.y+5,d.z);if(activeCity==='hangzhou'){if(d.index===1)d.point.y=19;if(d.index===3)d.point.y=40;}}
}
function switchCity(key){
 if(!cityConfigs[key])return;
 if(key==='chengdu'&&!chengdu){chengdu=createChengdu({base,ground,water,facade,roofmat,glass,gold});scene.add(chengdu.group);Object.assign(cityConfigs.chengdu,chengdu);}
 activeCity=key;const config=cityConfigs[key];world.visible=key==='hangzhou';if(chengdu)chengdu.group.visible=key==='chengdu';destinations=config.destinations;
 selected=null;flight=null;roaming=false;roamIndex=0;controls.autoRotate=false;controls.target.set(0,2,0);camera.position.copy(homePosition());controls.update();setActive('tour',false);setActive('orbit',false);
 tabType='city';document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tabType));$('#detail').hidden=true;document.body.classList.remove('place-selected');
 $('#city-name').textContent=config.title;$('#city-seal').innerHTML=config.seal;$('#city-eyebrow').textContent=config.en+' · SPATIAL ATLAS';$('#city-subtitle').textContent=config.subtitle;$('#city-select').value=key;$('.nav-title span').textContent=destinations.length+' 处风景';$('#scene').setAttribute('aria-label',`可交互的${config.name}三维微缩沙盘`);document.title=config.title+' · 城市图鉴';$('#help-dialog h2').textContent=`把${config.name}，放在掌心。`;$('#help-dialog .eyebrow').textContent='EXPLORE '+config.en;
 renderLabels();renderList();$('#destinations').scrollTop=0;drawMap();toast('已来到'+config.name+' · '+destinations.length+' 处风景');
 try{localStorage.setItem('spatial-atlas-city',key);}catch{}
}
renderLabels();

function renderList(){const list=$('#destinations');list.innerHTML='';destinations.filter(d=>d.type===tabType).forEach(d=>{const btn=document.createElement('button');btn.dataset.place=String(d.index);btn.className='destination'+(selected===d.index?' active':'');btn.innerHTML=`<span class="number">${String(d.index+1).padStart(2,'0')}</span><span><b>${d.name}</b><small>${d.en}</small></span><span class="arrow">↗</span>`;btn.onclick=()=>selectDestination(d.index);list.append(btn);});window.dispatchEvent(new Event('atlas-list-rendered'));}
function fly(target,position,duration=1700){flight={start:performance.now(),duration,from:camera.position.clone(),fromTarget:controls.target.clone(),to:position.clone(),target:target.clone()};controls.autoRotate=false;setActive('orbit',false);}
function selectDestination(i,byTour=false){selected=i;const d=destinations[i];window.dispatchEvent(new CustomEvent('atlas-place',{detail:{city:activeCity,place:String(i),title:d.name}}));if(!byTour){roaming=false;setActive('tour',false);}document.body.classList.add('place-selected');$('#detail').hidden=false;$('#detail-number').textContent=`${String(i+1).padStart(2,'0')} / EXPLORE ${cityConfigs[activeCity].en}`;$('#detail-title').textContent=d.name;$('#detail-en').textContent=d.en;$('#detail-copy').textContent=d.copy;$('#detail-tags').innerHTML=d.tags.split(',').map(x=>`<span>${x}</span>`).join('');destinations.forEach(x=>x.el.classList.toggle('active',x.index===i));tabType=d.type;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tabType));renderList();const t=new THREE.Vector3(d.x,d.y,d.z);fly(t,t.clone().add(new THREE.Vector3(.72,.6,1).normalize().multiplyScalar(d.distance*(innerWidth<600?1.6:1))));}
function home(){window.dispatchEvent(new Event('atlas-leave'));selected=null;roaming=false;setActive('tour',false);$('#detail').hidden=true;document.body.classList.remove('place-selected');destinations.forEach(d=>d.el.classList.remove('active'));renderList();fly(new THREE.Vector3(0,2,0),homePosition(),1800);}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('visible'),2400);}
const icons={home:'<path d="M3 10L12 3l9 7v11h-6v-7H9v7H3z"/>',orbit:'<ellipse cx="12" cy="12" rx="10" ry="5" transform="rotate(-35 12 12)"/><path d="M12 4v16"/>',tour:'<circle cx="12" cy="12" r="9"/><path d="m10 8 6 4-6 4z"/>',water:'<path d="M2 6q3-4 6 0t6 0t8 0M2 12q3-4 6 0t6 0t8 0M2 18q3-4 6 0t6 0t8 0"/>',view:'<path d="m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2zM9 3v16M15 5v16"/>',labels:'<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0"/><circle cx="12" cy="10" r="2.5"/>',photo:'<path d="M3 7h4l2-3h6l2 3h4v14H3z"/><circle cx="12" cy="13" r="4"/>',full:'<path d="M3 9V3h6M15 3h6v6M21 15v6h-6M9 21H3v-6"/>'};
const dockItems=[['home','全景'],['orbit','环游'],['tour','漫游'],['water','涟漪'],['view','俯视'],['labels','地标'],['photo','拍照'],['full','全屏']];$('#dock').innerHTML=dockItems.map(([id,label])=>`<button id="tool-${id}" aria-label="${label}" title="${label}"><svg viewBox="0 0 24 24">${icons[id]}</svg><span>${label}</span></button>`).join('');function setActive(id,val){$('#tool-'+id)?.classList.toggle('active',val);$('#tool-'+id)?.setAttribute('aria-pressed',String(val));}setActive('labels',true);
$('#tool-home').onclick=home;$('#tool-orbit').onclick=()=>{flight=null;roaming=false;setActive('tour',false);controls.autoRotate=!controls.autoRotate;setActive('orbit',controls.autoRotate);toast(controls.autoRotate?'正在环绕当前风景':'已暂停环游');};
$('#tool-tour').onclick=()=>{roaming=!roaming;setActive('tour',roaming);if(roaming){roamIndex=selected??0;selectDestination(roamIndex,true);roamTime=performance.now();toast('漫游已开启 · 每 9 秒探访下一处风景');}else toast('漫游已暂停');};
$('#tool-water').onclick=()=>{runningWater=!runningWater;setActive('water',runningWater);toast(runningWater?'水面涟漪与舟车动画已开启':'水面与舟车已静止');};$('#tool-view').onclick=()=>{roaming=false;setActive('tour',false);fly(new THREE.Vector3(0,0,0),new THREE.Vector3(0,330,.1));toast('俯瞰山水全貌');};$('#tool-labels').onclick=()=>{showLabels=!showLabels;$('#labels').style.display=showLabels?'block':'none';setActive('labels',showLabels);};
$('#tool-photo').onclick=()=>{renderer.render(scene,camera);const a=document.createElement('a');a.download=`${cityConfigs[activeCity].title}-${mode}-${Date.now()}.png`;a.href=renderer.domElement.toDataURL('image/png');a.click();toast('当前三维画面已保存为 PNG');};
$('#tool-full').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{clean=!clean;document.body.classList.toggle('clean',clean);toast('沉浸模式 · 再次点击全屏退出');}};
$('#minimap').onclick=home;$('#close-detail').onclick=()=>{$('#detail').hidden=true;document.body.classList.remove('place-selected');};$('#closer').onclick=()=>{if(selected===null)return;const d=destinations[selected],t=new THREE.Vector3(d.x,d.y,d.z);fly(t,t.clone().add(new THREE.Vector3(.65,.35,.9).normalize().multiplyScalar(d.distance*.57)));};$('#orbit-place').onclick=()=>{flight=null;roaming=false;setActive('tour',false);controls.autoRotate=true;setActive('orbit',true);};
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>{tabType=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));renderList();};
function zoom(k){flight=null;camera.position.sub(controls.target).multiplyScalar(k).clampLength(controls.minDistance,controls.maxDistance).add(controls.target);controls.update();}$('#zoom-in').onclick=()=>zoom(.8);$('#zoom-out').onclick=()=>zoom(1.25);
$('#help').onclick=()=>$('#help-dialog').showModal();$('#close-help').onclick=()=>$('#help-dialog').close();
const modes={day:{bg:'#e5ece3',hemi:1.9,sun:2.7,sunColor:'#fff8dd',water:'#58b3ab',exposure:1.08,emissive:0},sunset:{bg:'#ead8bd',hemi:1.8,sun:3.6,sunColor:'#ffac63',water:'#7da99b',exposure:1.15,emissive:.12},night:{bg:'#132c36',hemi:.65,sun:.65,sunColor:'#8ab8d4',water:'#286a77',exposure:1.05,emissive:.8}};
let lightTween=null;function setMode(key){mode=key;document.body.classList.toggle('night',key==='night');document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===key));lightTween={start:performance.now(),bg:scene.background.clone(),color:sun.color.clone(),water:water.color.clone(),hemi:hemi.intensity,sun:sun.intensity,exposure:renderer.toneMappingExposure,emissive:facade.emissiveIntensity,to:modes[key]};}document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
controls.addEventListener('start',()=>{flight=null;if(roaming){roaming=false;setActive('tour',false);}controls.autoRotate=false;setActive('orbit',false);});
document.addEventListener('keydown',e=>{if(e.target.closest('button,input,textarea,select,dialog'))return;if(e.code==='Space'){e.preventDefault();$('#tool-tour').click();}if(e.key.toLowerCase()==='h')home();if(e.key.toLowerCase()==='l')$('#tool-labels').click();if(e.key==='Escape'){if(clean){clean=false;document.body.classList.remove('clean');}else home();}});
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();if(selected===null&&!flight)camera.position.copy(homePosition());renderer.setSize(innerWidth,innerHeight);});
renderList();
// Mini-map drawn from the same geometry rather than a decorative placeholder.
const ctx=$('#map').getContext('2d');function mapPoint(x,z){return[(x+145)/290*240,(z+107)/214*170];}function drawMap(){if(activeCity==='chengdu'){chengdu.drawMap(ctx,mapPoint);drawMapTarget();return;}ctx.fillStyle='#e0e6d1';ctx.fillRect(0,0,240,170);for(let x=-140;x<140;x+=5)for(let z=-102;z<102;z+=5){let h=height(x,z);if(h>1){ctx.fillStyle=`rgba(100,140,89,${Math.min(h/65,.6)})`;let p=mapPoint(x,z);ctx.fillRect(...p,5,5);}}ctx.lineCap='round';ctx.strokeStyle='#6fae9c';ctx.lineWidth=8;ctx.beginPath();riverPts.forEach((p,i)=>{let q=mapPoint(p.x,p.z);i?ctx.lineTo(...q):ctx.moveTo(...q);});ctx.stroke();ctx.fillStyle='#7eb7a1';ctx.beginPath();lakePoints.forEach((p,i)=>{let q=mapPoint(...p);i?ctx.lineTo(...q):ctx.moveTo(...q);});ctx.closePath();ctx.fill();ctx.fillStyle='#9dac98';for(let i=0;i<buildings.length;i+=3){let p=mapPoint(buildings[i].x,buildings[i].z);ctx.fillRect(...p,1.2,1.6);}drawMapTarget();}
function drawMapTarget(){let p=mapPoint(controls.target.x,controls.target.z);ctx.beginPath();ctx.arc(...p,7,0,TAU);ctx.strokeStyle='#3e9384';ctx.lineWidth=1.3;ctx.stroke();ctx.beginPath();ctx.arc(...p,3,0,TAU);ctx.fillStyle='#3e9384';ctx.fill();}
let clock=new THREE.Clock(),elapsed=0,lastFps=0,frames=0,lastMap=0;const projected=new THREE.Vector3();
function animate(now){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);if(runningWater)elapsed+=dt;waterUniform.time.value=elapsed;waterUniform.night.value=mode==='night'?1:0;
if(lightTween){const t=Math.min((now-lightTween.start)/1100,1),a=lightTween,to=a.to;scene.background.copy(a.bg).lerp(new THREE.Color(to.bg),t);scene.fog.color.copy(scene.background);ground.material.color.copy(scene.background);sun.color.copy(a.color).lerp(new THREE.Color(to.sunColor),t);water.color.copy(a.water).lerp(new THREE.Color(to.water),t);glass.emissive.set('#78b7ad');glass.emissiveIntensity=mode==='night'?.12*t:0;gold.emissive.set('#d4a14f');gold.emissiveIntensity=mode==='night'?.15*t:0;hemi.intensity=THREE.MathUtils.lerp(a.hemi,to.hemi,t);sun.intensity=THREE.MathUtils.lerp(a.sun,to.sun,t);renderer.toneMappingExposure=THREE.MathUtils.lerp(a.exposure,to.exposure,t);facade.emissiveIntensity=THREE.MathUtils.lerp(a.emissive,to.emissive,t);if(t===1)lightTween=null;}
if(flight){const t=Math.min((now-flight.start)/flight.duration,1),ease=t*t*(3-2*t);camera.position.lerpVectors(flight.from,flight.to,ease);controls.target.lerpVectors(flight.fromTarget,flight.target,ease);if(t===1)flight=null;}
if(roaming&&now-roamTime>9000){roamIndex=(roamIndex+1)%destinations.length;selectDestination(roamIndex,true);roamTime=now;}if(roaming&&!flight){controls.autoRotate=true;}
controls.update();
if(activeCity==='chengdu')chengdu.update(elapsed,mode);
if(activeCity==='hangzhou')for(const b of boats){if(b.type==='river'){let t=(b.a+elapsed*b.speed)%1,p=riverPath.getPoint(t),tangent=riverPath.getTangent(t);b.g.position.set(p.x,.68+Math.sin(elapsed*1.5+b.a)*.035,p.z);b.g.rotation.y=Math.atan2(tangent.x,tangent.z);}else{let a=b.a+elapsed*b.speed;b.g.position.set(lake.x+Math.cos(a)*b.r,.65+Math.sin(elapsed*2+b.a)*.04,lake.z+Math.sin(a)*b.r*.75);b.g.rotation.y=-a;}}
if(activeCity==='hangzhou')for(const c of traffic)c.car.position.z=((elapsed*c.speed+c.start*c.len)%c.len+c.len)%c.len-c.len/2;
if(showLabels){const compact=document.body.classList.contains('mobile-layout'),occupied=[];for(const d of [...destinations].sort((a,b)=>(a.index===selected?-1:b.index===selected?1:0))){projected.copy(d.point).project(camera);let x=(projected.x*.5+.5)*innerWidth,y=(-projected.y*.5+.5)*innerHeight;let visible=projected.z<1&&projected.z>-1&&x>0&&x<innerWidth&&y>0&&y<innerHeight;const distance=camera.position.distanceTo(d.point);if(distance>330&&d.index!==selected&&d.index%3===2)visible=false;if(compact&&(x<65||x>innerWidth-65||y<110||y>innerHeight-100))visible=false;if(visible&&d.index!==selected&&(compact&&occupied.length>=4||occupied.some(p=>Math.abs(p[0]-x)<(compact?145:90)&&Math.abs(p[1]-y)<(compact?54:31))))visible=false;if(visible)occupied.push([x,y]);d.el.style.display=visible?'block':'none';if(visible)d.el.style.transform=`translate(${x}px,${y}px) translate(-50%,-100%)`;}}
$('.compass svg').style.transform=`rotate(${-controls.getAzimuthalAngle()*180/Math.PI}deg)`;if(now-lastMap>150){drawMap();lastMap=now;}renderer.render(scene,camera);frames++;if(now-lastFps>1600){$('#fps').textContent=`${Math.round(frames*1000/(now-lastFps))} FPS`;frames=0;lastFps=now;}}
$('#city-select').onchange=e=>switchCity(e.target.value);
try{const saved=localStorage.getItem('spatial-atlas-city');if(saved==='chengdu')switchCity(saved);}catch{}
requestAnimationFrame(animate);setTimeout(()=>{$('#loading').style.opacity='0';setTimeout(()=>$('#loading').remove(),650);},350);

import './sound.js';
import './mobile.js';

const entry=new URLSearchParams(location.search);if(['hangzhou','chengdu'].includes(entry.get('city'))){switchCity(entry.get('city'));const index=Number(entry.get('place'));if(entry.has('place')&&Number.isInteger(index)&&destinations[index])selectDestination(index);}

function frameDrawer(){if(document.body.classList.contains('mobile-layout')&&!$('#detail').hidden){const h=$('#detail').getBoundingClientRect().height;camera.setViewOffset(innerWidth,innerHeight,0,Math.min(h*.5,innerHeight*.25),innerWidth,innerHeight);}else camera.clearViewOffset();}
window.addEventListener('atlas-drawer',()=>requestAnimationFrame(frameDrawer));$('#detail').addEventListener('transitionend',frameDrawer);window.addEventListener('resize',frameDrawer);
