import{openFloating}from'./site/floating-player.js';
import {warm,player,poster,startPlayback} from './site/media-cache.js';
import {state as account,refreshUser,api as accountAPI,loginURL} from './site/session.js';
const $=s=>document.querySelector(s),audio=new Audio();audio.loop=true;audio.preload='metadata';audio.volume=.45;
const tracks={chengdu:{title:'成都 · 钢琴演奏版'},hangzhou:{title:'青城山下白素贞 · 前世今生'}};let city,bgmWanted=true;
function paint(){const on=!audio.paused;$('.sound-card').classList.toggle('spinning',on);$('.record i').textContent=on?'Ⅱ':'▶';$('#music-play').setAttribute('aria-label',on?'暂停背景音乐':'播放背景音乐');$('#music-status').textContent=on?'点击暂停 · 循环播放':'点击 CD · 随城而听';}
async function play(){try{await audio.play();paint();}catch{$('#music-status').textContent='轻触页面 · 开启城市音乐';}}
function change(){const next=$('#city-select').value;if(next===city)return;if(city!==undefined)window.dispatchEvent(new Event('atlas-leave'));const resume=true;bgmWanted=true;city=next;audio.src=`audio/${city}.mp3`;$('#track-title').textContent=tracks[city].title;$('#track-title').title=tracks[city].title;paint();if(resume)play();}
$('#city-select').addEventListener('change',change);queueMicrotask(change);$('.sound-card').onclick=()=>{if(audio.paused){bgmWanted=true;play();}else{bgmWanted=false;audio.pause();paint();}};audio.onplay=paint;audio.onpause=paint;audio.onerror=()=>$('#music-status').textContent='加载失败 · 点击重试';
const attachmentDrafts=new Map();
const draftKey=c=>'atlas-draft:'+c.city+':'+c.place+':'+(account.user?.id||'guest');
function saveDraft(){if(!context)return;try{localStorage.setItem(draftKey(context),$('#notes-form').elements.message.value);}catch{}attachmentDrafts.set(draftKey(context),[...$('#notes-file').files]);}
function restoreDraft(){if(!context)return;try{const key=draftKey(context),guest='atlas-draft:'+context.city+':'+context.place+':guest';$('#notes-form').elements.message.value=localStorage.getItem(key)||localStorage.getItem(guest)||'';}catch{}const files=attachmentDrafts.get(draftKey(context));if(files?.length){const transfer=new DataTransfer();files.forEach(f=>transfer.items.add(f));$('#notes-file').files=transfer.files;file.onchange();}$('#notes-form').elements.name.value=account.user?.username||'';}
let context=null,epoch=0,page=1,playlist=[],track=0;const narration=new Audio(),file=$('#notes-file'),status=$('#notes-status');const headers=()=>({'X-CSRF-Token':account.csrf});
let uploadLimits={image:5,audio:50,video:80};fetch('/api/config').then(r=>r.json()).then(d=>{uploadLimits=d.limits;hint();}).catch(()=>{});refreshUser().then(()=>{const link=$('#city-account');link.querySelector('span').textContent=account.user?account.user.username:'登录 / 注册';link.href=loginURL();$('#notes-form').elements.name.value=account.user?.username||'';}).catch(()=>{});
function hint(){ $('#attachment-hint').textContent=`图片 ${uploadLimits.image}MB · 音频 ${uploadLimits.audio}MB · 视频 ${uploadLimits.video}MB`; }
function fileType(f){return f.type.startsWith('image/')?'image':f.type.startsWith('audio/')?'audio':'video';}
function stopNarration(){narration.pause();narration.removeAttribute('src');playlist=[];audio.volume=.45;$('#narration-controls').hidden=true;}
window.addEventListener('atlas-leave',()=>{saveDraft();epoch++;context=null;stopNarration();});
function narrationPaint(){const on=!narration.paused;$('#narration-toggle').textContent=on?'暂停解说':'播放解说';$('#narration-status').textContent=playlist.length?`${track+1} / ${playlist.length} · ${playlist[track].message.slice(0,32)}`:'';audio.volume=on?.10:.45;}
async function playNarration(){if(!playlist.length)return;try{await narration.play();}catch{$('#narration-status').textContent='点击「播放解说」开始收听';}}
function pickNarration(){if(!playlist.length)return;narration.src=playlist[track].media;narrationPaint();playNarration();}
narration.onended=()=>{track=(track+1)%playlist.length;pickNarration();};narration.onplay=narrationPaint;narration.onpause=narrationPaint;narration.onerror=()=>$('#narration-status').textContent='解说加载失败，可切换下一条';$('#narration-toggle').onclick=()=>narration.paused?playNarration():narration.pause();$('#narration-next').onclick=()=>{track=(track+1)%playlist.length;pickNarration();};
file.multiple=true;file.onchange=()=>{const fs=[...file.files];if(fs.length>9||(fs.length>1&&fs.some(f=>fileType(f)!=='image'))){file.value='';status.textContent='可选择最多9张图片，或一个音频/视频';return;}const over=fs.find(f=>f.size>uploadLimits[fileType(f)]*1024**2);if(over){file.value='';status.textContent=`${over.name} 超过大小限制`;return;}$('#audio-category').hidden=fs[0]?.type.startsWith('audio/')!==true;$('#attachment-hint').textContent=fs.length?fs.map(f=>f.name).join(' · '):'最多9张图片，或一个音频/视频';};$('#audio-category').hidden=true;
const modal=$('#media-dialog');let resumeBgm=false,resumeNarration=false,gallery=[],galleryIndex=0,galleryRequest=0,galleryPlace=null;
function clearStage(){$('#media-stage').querySelectorAll('audio,video').forEach(m=>m.pause());$('#media-stage').replaceChildren();}
function showItem(){openFloating(gallery,galleryIndex,()=>{galleryRequest++;gallery=[];if(resumeBgm)play();if(resumeNarration)playNarration();},{onCreate:()=>{if(!account.user){location.href=loginURL();return;}if(String(context?.place)!==galleryPlace){document.querySelector('#destinations [data-place="'+galleryPlace+'"]')?.click();}setTimeout(()=>{document.querySelector('#detail').dataset.detent='full';window.dispatchEvent(new Event('atlas-drawer'));$('#notes-form').scrollIntoView({behavior:'smooth',block:'center'});$('#notes-form').elements.message.focus();},250);}});}
function beginPreview(){resumeBgm=!audio.paused;resumeNarration=!narration.paused;audio.pause();narration.pause();}
function openMedia(n){galleryRequest++;gallery=[n];galleryIndex=0;beginPreview();showItem();}
async function openGallery(place,type,selectedId){const request=++galleryRequest,c=$('#city-select').value;galleryPlace=String(place);beginPreview();clearStage();$('#media-title').textContent='正在打开景点影像…';$('#media-counter').textContent='';$('#media-prev').disabled=$('#media-next').disabled=true;try{const rows=[];let page=1,pages=1;do{const r=await fetch(`/api/notes?city=${c}&place=${place}&page=${page}`);if(!r.ok)throw Error();const d=await r.json();rows.push(...d.items);pages=d.pages;page++;if(request!==galleryRequest)return;}while(page<=pages);gallery=rows;galleryIndex=Math.max(0,selectedId?gallery.findIndex(n=>n.id===selectedId):gallery.findIndex(n=>type==='narration'?n.category==='narration':type==='voice'?n.media_type==='audio':n.media_type===type));if(!gallery.length){$('#media-title').textContent='该景点暂无此类媒体';return;}showItem();}catch{if(request===galleryRequest)$('#media-title').textContent='加载失败，请关闭后重试';}}
$('#media-prev').onclick=()=>{if(galleryIndex>0){galleryIndex--;showItem();}};$('#media-next').onclick=()=>{if(galleryIndex<gallery.length-1){galleryIndex++;showItem();}};
$('#media-max').onclick=async()=>{if(document.fullscreenElement){await document.exitFullscreen();return;}try{await modal.requestFullscreen();}catch{modal.classList.toggle('media-expanded');}};
modal.addEventListener('keydown',e=>{if(e.target.matches('input,video,audio'))return;if(e.key==='ArrowLeft'){$('#media-prev').click();e.preventDefault();}if(e.key==='ArrowRight'){$('#media-next').click();e.preventDefault();}});
$('#media-close').onclick=()=>modal.close();modal.addEventListener('close',()=>{galleryRequest++;clearStage();gallery=[];modal.classList.remove('media-expanded');if(document.fullscreenElement===modal)document.exitFullscreen();if(resumeBgm)play();if(resumeNarration)playNarration();});
function render(data){warm(data.items.slice(0,1));$('#notes-list').replaceChildren();$('#notes-count').textContent=data.total+' 条足迹';$('#notes-page').textContent=`${data.page} / ${data.pages}`;$('#notes-prev').disabled=page<=1;$('#notes-next').disabled=page>=data.pages;if(!data.items.length){const p=document.createElement('p');p.textContent='还没有足迹，写下你的第一段回忆。';$('#notes-list').append(p);}for(const n of data.items){const el=document.createElement('article'),head=document.createElement('small'),body=document.createElement('p');head.textContent=`${n.name} · ${new Date(n.created).toLocaleDateString('zh-CN')}`;body.textContent=n.message;el.append(head,body);body.style.cursor='pointer';body.title='打开景点手记';body.onclick=()=>openGallery(context.place,'all',n.id);const read=document.createElement('button');read.textContent='翻阅手记 ↑';read.onclick=()=>openGallery(context.place,'all',n.id);el.append(read);if(n.media){const b=document.createElement('button');b.className='media-preview';b.textContent=n.media_type==='image'?'▧ 查看大图':n.media_type==='video'?'▶ 播放录像':n.category==='narration'?'♫ 收听景点解说':'♪ 收听语音留言';if(n.media_type==='image'||(n.media_type==='video'&&poster(n))){const img=document.createElement('img');img.src=n.media_type==='video'?poster(n):n.media;img.loading='lazy';img.alt=n.message;b.prepend(img);}b.onclick=()=>openGallery(context.place,n.media_type==='audio'?(n.category==='narration'?'narration':'voice'):n.media_type,n.id);el.append(b);}if(n.can_delete){const d=document.createElement('button');d.className='delete-note';d.textContent='删除';d.onclick=async()=>{if(!confirm('删除这条留言及附件？'))return;const r=await fetch('/api/notes/'+n.id,{method:'DELETE',headers:headers()});if(r.ok){await load();await refreshPlaylist(false);badges();}else status.textContent='删除失败，请重试';};el.append(d);}$('#notes-list').append(el);}$('#notes-list').scrollTop=0;}
async function load(){if(!context)return;const tokenEpoch=++epoch;$('#notes-caption').textContent=context.title+' · 历史留言';status.textContent='正在读取…';try{const r=await fetch(`/api/notes?city=${context.city}&place=${context.place}&page=${page}`,{headers:headers(),signal:AbortSignal.timeout(6000)});if(!r.ok)throw Error();const data=await r.json();if(tokenEpoch!==epoch)return;render(data);status.textContent=account.user?'公开留言 · 请勿填写个人隐私':'登录后可以上传和留言';}catch{if(tokenEpoch===epoch)status.textContent='加载失败，请在线上版本重试';}}
async function refreshPlaylist(autoplay){const c=context;if(!c)return;try{const r=await fetch(`/api/notes?city=${c.city}&place=${c.place}&playlist=1`);const d=await r.json();if(c!==context)return;const old=narration.src;playlist=d.items;$('#narration-controls').hidden=!playlist.length;if(!playlist.length){stopNarration();return;}track=Math.max(0,playlist.findIndex(n=>new URL(n.media,location.href).href===old));if(autoplay)pickNarration();else if(!playlist.some(n=>new URL(n.media,location.href).href===old)){narration.pause();narration.src=playlist[track].media;}narrationPaint();}catch{}}
window.addEventListener('atlas-place',e=>{saveDraft();stopNarration();context=e.detail;page=1;$('#notes-form').reset();$('#audio-category').hidden=true;hint();restoreDraft();load();refreshPlaylist(true);});$('#notes-prev').onclick=()=>{page--;load();};$('#notes-next').onclick=()=>{page++;load();};
let activeUpload=null,pendingSubmission=null;
$('#cancel-upload').onclick=()=>activeUpload?.abort();
function uploadFile(f){return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();activeUpload=xhr;xhr.open('POST','/api/upload');xhr.timeout=240000;xhr.setRequestHeader('X-CSRF-Token',account.csrf);xhr.setRequestHeader('Content-Type',f.type||'application/octet-stream');$('#upload-panel').hidden=false;$('#upload-name').textContent=f.name;$('#upload-progress').value=0;$('#cancel-upload').hidden=false;xhr.upload.onprogress=e=>{if(e.lengthComputable){const pct=Math.min(100,Math.floor(e.loaded/e.total*100));$('#upload-progress').value=pct;$('#upload-detail').textContent=`${pct}% · ${(e.loaded/1024**2).toFixed(1)} / ${(e.total/1024**2).toFixed(1)} MB`;}};xhr.upload.onload=()=>{$('#upload-detail').textContent='传输完成，服务器正在保存…';};xhr.onload=()=>{activeUpload=null;$('#cancel-upload').hidden=true;try{const d=JSON.parse(xhr.responseText);if(xhr.status>=200&&xhr.status<300)resolve(d);else reject(Error(d.error||'上传失败'));}catch{reject(Error('服务器响应异常，请重试'));}};xhr.onerror=()=>{activeUpload=null;reject(Error('网络中断，可重新提交'));};xhr.onabort=()=>{activeUpload=null;reject(Error('已取消上传'));};xhr.ontimeout=()=>{activeUpload=null;reject(Error('上传超时，请重试'));};xhr.send(f);});}
$('#notes-form').onsubmit=async e=>{e.preventDefault();if(!context)return;await refreshUser();if(!account.user){saveDraft();location.href='/account/?return='+encodeURIComponent(location.pathname+'?city='+context.city+'&place='+context.place+'&compose=1');return;}const target=context,f=e.target,b=f.querySelector('button[type=submit]'),message=f.elements.message.value.trim(),attachments=[...file.files],attachment=attachments[0];if(!message)return;try{const config=await fetch('/api/config').then(r=>r.json());uploadLimits=config.limits;}catch{}if(attachments.some(f=>f.size>uploadLimits[fileType(f)]*1024**2)){status.textContent=`该类型文件不得超过 ${uploadLimits[fileType(attachment)]}MB`;return;}const category=$('#audio-category').value;const signature=JSON.stringify([target.city,target.place,message,category,attachments.map(f=>[f.name,f.size,f.lastModified])]);if(!pendingSubmission||pendingSubmission.signature!==signature)pendingSubmission={signature,request_id:Array.from(crypto.getRandomValues(new Uint8Array(16)),n=>n.toString(16).padStart(2,'0')).join('')};b.disabled=true;status.textContent='正在提交…';try{pendingSubmission.uploaded??=[];for(let i=pendingSubmission.uploaded.length;i<attachments.length;i++){const d=await uploadFile(attachments[i]);pendingSubmission.uploaded.push(d);}pendingSubmission.media=pendingSubmission.uploaded[0]?.media;pendingSubmission.images=pendingSubmission.uploaded.filter(x=>x.media_type==='image').map(x=>x.media);$('#upload-detail').textContent='正在保存留言…';await accountAPI('/api/notes',{method:'POST',body:JSON.stringify({...target,message,media:pendingSubmission.media||'',images:pendingSubmission.images||[],category,request_id:pendingSubmission.request_id})});pendingSubmission=null;try{localStorage.removeItem(draftKey(target));localStorage.removeItem('atlas-draft:'+target.city+':'+target.place+':guest');}catch{}attachmentDrafts.delete(draftKey(target));$('#upload-detail').textContent='上传与留言保存完成';if(context===target){f.reset();f.elements.name.value=account.user.username;file.onchange();page=1;await load();refreshPlaylist(false);}badges();}catch(err){status.textContent=err.message||'提交失败';$('#upload-detail').textContent=err.message;}finally{b.disabled=false;$('#cancel-upload').hidden=true;}};
let summary=[];async function badges(){const c=$('#city-select').value;try{const r=await fetch('/api/media-summary?city='+c);const d=await r.json();if(c!==$('#city-select').value)return;summary=d;paintBadges();}catch{}}
const mediaIcons={image:'<rect x="3" y="4" width="18" height="16" rx="3"/><circle cx="8" cy="9" r="1.5"/><path d="m4 17 5-5 4 4 3-3 4 4"/>',narration:'<path d="M9 18V5l11-2v13M9 8l11-2"/><ellipse cx="6" cy="18" rx="3" ry="2"/><ellipse cx="17" cy="16" rx="3" ry="2"/>',video:'<rect x="3" y="5" width="14" height="14" rx="3"/><path d="m17 10 4-3v10l-4-3"/>',voice:'<rect x="9" y="3" width="6" height="12" rx="3"/><path d="M6 11v2a6 6 0 0 0 12 0v-2M12 19v3"/>'};
function paintBadges(){const targets=[...document.querySelectorAll('#labels .label')].map((el,i)=>[el,String(i),false]).concat([...document.querySelectorAll('#destinations .destination')].map(el=>[el,el.dataset.place,true]));for(const [el,place,list] of targets){el.querySelector('.media-badge')?.remove();const rows=summary.filter(r=>r.place===place);const types=['image','narration','video','voice'].filter(type=>rows.some(r=>type==='narration'?r.category==='narration':type==='voice'?r.type==='audio'&&r.category!=='narration':r.type===type));if(!types.length)continue;const group=document.createElement('span');group.className='media-badge';for(const type of types){const icon=document.createElement('span'),name={image:'照片',narration:'解说',video:'视频',voice:'语音'}[type];icon.className='media-icon';icon.tabIndex=0;icon.setAttribute('role','button');icon.title='查看'+name;icon.setAttribute('aria-label','查看'+name);icon.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true">'+mediaIcons[type]+'</svg>';icon.onclick=e=>{e.stopPropagation();e.preventDefault();openGallery(place,type);};icon.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.stopPropagation();e.preventDefault();openGallery(place,type);}};group.append(icon);}if(list){el.querySelector('b').append(group);}else el.append(group);}}
window.addEventListener('atlas-list-rendered',paintBadges);
$('#city-select').addEventListener('change',()=>{summary=[];badges();});queueMicrotask(badges);
const header=document.querySelector('header');header.append($('.sound-card'));$('.sound-card').setAttribute('role','button');$('.sound-card').tabIndex=0;$('.sound-card').onkeydown=e=>{if(e.code==='Space'||e.code==='Enter'){e.preventDefault();e.stopPropagation();$('.sound-card').click();}};$('#music-play').tabIndex=-1;function fitMusic(){document.querySelector('.navigator').style.top=(header.getBoundingClientRect().bottom+14)+'px';}new ResizeObserver(fitMusic).observe(header);fitMusic();

$('#close-detail').addEventListener('click',()=>window.dispatchEvent(new Event('atlas-leave')));

function unlockBgm(e){if(!bgmWanted||!audio.paused||document.querySelector('dialog[open]')||e.target.closest('.sound-card,#city-select'))return;play();}document.addEventListener('pointerdown',unlockBgm);document.addEventListener('keydown',unlockBgm);

let composeRequested=new URLSearchParams(location.search).get('compose')==='1';window.addEventListener('atlas-place',()=>{if(composeRequested){composeRequested=false;setTimeout(()=>{document.querySelector('#detail').dataset.detent='full';window.dispatchEvent(new Event('atlas-drawer'));$('#notes-form').scrollIntoView({behavior:'smooth',block:'center'});$('#notes-form').elements.message.focus();},500);}});

$('#notes-form').elements.message.addEventListener('input',saveDraft);
file.addEventListener('change',saveDraft);window.addEventListener('pagehide',saveDraft);
window.addEventListener('atlas-read-stories',()=>{if(!context)return;if($('#notes-count').textContent.startsWith('0 ')){$('#notes-caption').textContent='这里还没有手记，欢迎写下第一段回忆。';$('#place-notes').scrollIntoView({block:'start'});}else openGallery(context.place,'all');});
window.addEventListener('atlas-compose',async()=>{if(!context)return;saveDraft();try{await refreshUser();}catch{status.textContent='无法确认登录状态，请检查网络后重试';return;}if(!account.user){location.href='/account/?return='+encodeURIComponent(location.pathname+'?city='+context.city+'&place='+context.place+'&compose=1');return;}restoreDraft();$('#notes-form').scrollIntoView({block:'start'});$('#notes-form').elements.message.focus({preventScroll:true});});

window.addEventListener('atlas-auth',()=>{if(context&&!$('#notes-form').elements.message.value)restoreDraft();});
